{% set name = "vulkan-validation-layers" %}
{% set version = "1.4.310" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7a723e9ea84c7782763fb082b25849f585bc8000d37f1b5dec44919abea1a58

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pkg-config
  host:
    - libxcb             # [linux]
    - xorg-libx11        # [linux]
    - xorg-libxrandr     # [linux]
    - xorg-xorgproto     # [linux]
    - wayland            # [linux]
    - wayland-protocols  # [linux]

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\VkLayer_khronos_validation.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\VkLayer_khronos_validation.json exit 1  # [win]
    - test -d $PREFIX/share/vulkan/explicit_layer.d/  # [unix]
    - test -f $PREFIX/share/vulkan/explicit_layer.d/VkLayer_khronos_validation.json  # [unix]
    - test -f $PREFIX/lib/libVkLayer_khronos_validation${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/KhronosGroup/Vulkan-ValidationLayers
  summary: 'Vulkan validation layers to assist developers in the correct usage of the API.'
  description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work.
    By design, minimal error checking is done inside a Vulkan driver. Applications have
    full control and responsibility for correct operation. Any errors in how Vulkan is
    used can result in a crash. This project provides Vulkan validation layers that can
    be enabled to assist development by enabling developers to verify their applications
    correct use of the Vulkan API.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JarrettSJohnson
