{% set name = "vulkan-validation-layers" %}
{% set version = "1.3.290" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/KhronosGroup/Vulkan-ValidationLayers/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 37fd611f1c5c5879a68c6f63b09e600a3858f519aa147a2535961fa3d8e889ae

build:
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pkg-config
  host:
    - libxcb             # [linux]
    - xorg-libx11        # [linux]
    - xorg-libxrandr     # [linux]
    - wayland            # [linux]
    - wayland-protocols  # [linux]

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\\bin\\VkLayer_khronos_validation.dll exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\bin\\VkLayer_khronos_validation.json exit 1  # [win]
    - test -d $PREFIX/share/vulkan/explicit_layer.d/  # [unix]
    - test -f $PREFIX/share/vulkan/explicit_layer.d/VkLayer_khronos_validation.json  # [unix]
    - test -f $PREFIX/lib/libVkLayer_khronos_validation${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/KhronosGroup/Vulkan-ValidationLayers
  summary: 'Vulkan validation layers to assist developers in the correct usage of the API.'
  description: |
    Vulkan is an Explicit API, enabling direct control over how GPUs actually work.
    By design, minimal error checking is done inside a Vulkan driver. Applications have
    full control and responsibility for correct operation. Any errors in how Vulkan is
    used can result in a crash. This project provides Vulkan validation layers that can
    be enabled to assist development by enabling developers to verify their applications
    correct use of the Vulkan API.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - JarrettSJohnson
